# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-19 03:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('stu_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('stu_name', models.CharField(max_length=50)),
            ],
        ),
    ]
