# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-19 05:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('tea_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('tea_name', models.CharField(max_length=50)),
            ],
        ),
    ]
